### ISSUE TITLE
`Prop` が非可述的であることを説明する

### ISSUE THREAD

**Issue by Seasawher** [lean-ja/lean-by-example#542]
TPiL に記述がある

---

imax i j の定義は次のように解釈すればよい。もし j が 0 でないなら、(x : α) → β は型 Sort (max i j) の項である。言い換えれば、α から β への依存関数型は、インデックスが i と j の最大値である宇宙に「住んで」いる。他方で、β が Sort 0、つまり Prop の項であるとしよう。この場合、α がどの階層的型宇宙に住んでいるかに関わらず、(x : α) → β も Sort 0 (Prop) の項となる。言い換えれば、β が α に依存する命題であれば、 ∀ x : α, β も命題であるということである。これは、Prop は単なるデータの型ではなく命題の型であるという解釈を反映している。そして以上のことは Prop をimpredicative(非可述的)にしている。

predicative(可述的)という用語は、20世紀初頭の数学基礎論の発展に由来する。当時、ポアンカレやラッセルといった論理学者が、集合論におけるパラドックスを、性質Aを持つ集合を量化することで性質Aを定義するときに生じる「悪循環」のせいにしたのである。任意の型 α に対して、α 上の全ての(一変数)述語からなる型 α → Prop (α の「べき型」)を作れることに注目してほしい。Prop のimpredicativity(非可述性)とは、α → Prop を量化した命題を作れることを意味する。特に、α 上の述語を全称量化することで、α 上の述語を定義することができ(∀ X : α → Prop, β と書くことで「全ての α 上の述語に対して β が成立する」という α 上の述語を定義することができ)、これはまさにかつて問題視された類の循環である。

---

Lean でラッセルのパラドックスをコードで再現してみると理解が深まるかもしれない

**Comment by Seasawher** [comment]
Girard のパラドックスをLeanで形式化した例がMathlibに存在する

https://github.com/leanprover-community/mathlib4/blob/a33cf03c4f57826d8dcb653483916aaeb0b55e65/Counterexamples/Girard.lean#L35-L48

**Comment by Seasawher** [comment]
MathlibにはRusselのパラドクスの証明もある

https://github.com/leanprover-community/mathlib4/blob/a33cf03c4f57826d8dcb653483916aaeb0b55e65/Mathlib/SetTheory/ZFC/Basic.lean#L1309-L1310

**Comment by Seasawher** [comment]
型宇宙 U が非可述語的であるとは、関数型 `U → U` の型が `U` 自身になることではないかと思った。

**Comment by Seasawher** [comment]
非可述的な型をPropを真似て帰納型として作ろうとしたらどうなるのか？

**Comment by spinylobster** [comment]
TAPLの23章に「23.10 非可述性」というセクションがありました。(日本語版ではP282)
僕はこれを読んでもまだよく理解できませんでしたが、一応参考文献として挙げておきます。
これによると、 System F の多相性は非可述的で ML の多相性は可述的らしいです。

>  一般に、（集合、型、 その他の） 定義は、定義されているそのもの自身が定義域に含まれるような量化子を含むとき、「非可述的」であるといわれる。

> 例えば System F では、型 T = `∀X.X→X` の型変数X は任意の型の上を動く。 これにはT自身も含まれる（これは、例えば、型Tに型Tの項を具体化して、T からTへの関数を得られるようにするためだ）。一方MLに見られる多相性はしばしば可述的である（または階層化されている）といわれる。これは型変数の値域が単型に制限されていて、量化子を含まないためである。「可述的」「非可述的」の用語は論理学に起因する。Quine [393] はこの歴史をわかりやすくまとめている。 

(393の論文は `Quine, Willard V. Quiddities: An Intermittently Philosophical Dictionary. Harvard  University Press, Cambridge, MA, 1987.` です)

> 今日では可述的集合論は構成的集合論であり、非可述的定義は前の段落できっちり説明した通りで、どの所属条件が類を定義していると考えるかには関係ない。

**Comment by Seasawher** [comment]
簡単な例でいうと、こういうのが非可述的という典型的な例かな

```lean
/- Prop が非可述的であるとは？  -/

-- α は型
opaque α : Type

-- pred の定義は、「任意の α 上の述語 P に対して P x」 だから、
-- pred が pred 自身に言及している。
def pred (x : α) := ∀ P : α → Prop, ¬ P x

-- pred 自身も α 上の述語
#check (pred : α → Prop)

-- なので pred は pred 自身に言及することができる！
example (h : pred x) : ¬ pred x := by
  have := h pred
  assumption
```
